public class Cat 
{
    private String name;
    private Integer size;
    public void setsize(integer s) {
        {
            if(s<=0) {
                System.debug('Size cannot be less than zero' +s);
                size=10;
            }
        else
            if(s>=0) {
                system.debug('You can add any value greater than 0' +s);
                size=s;
            }
        }
        
        
        
       // System.debug('name of the cat' +name);
      //  System.debug('size of the cat' +size);
    }

}